import Navbar from "./_components/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { Roboto } from "next/font/google";
import "./global.css";
import { ConcertProvider } from "./_context/ConcertContext";
import { ReservationProvider } from "./_context/ReservationContext";
import { UserProvider } from "./_context/UserContext";
import { ReservationHistoryProvider } from "./_context/ReservationHistoryContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <UserProvider>
              <ConcertProvider>
                <ReservationProvider>
                  <ReservationHistoryProvider>
                    <main>{children}</main>
                  </ReservationHistoryProvider>
                </ReservationProvider>
              </ConcertProvider>
            </UserProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
